apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: demo
  labels:
    app: client
spec:
    containers:
    - name: client
      image: busybox
      args:
      - "/bin/sh"
      - "-c"
      - "wget -T 2 10.244.198.196 -O -"
    nodeSelector:
      beta.kubernetes.io/os: linux
    restartPolicy: Never
