apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  namespace: demo
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 7080
    targetPort: 90
  clusterIP: 1.2.3.4
  loadBalancerIP: 5.6.7.8
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 11.22.33.44