apiVersion: v1
kind: Service
metadata:  
  name: my-nodeport-nginx
spec:
  selector:    
    app: nginx
  type: NodePort
  ports:  
  - name: http
    port: 6080
    targetPort: 80
    protocol: TCP